### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BridgeLee** [huzexi/OTB_Zoo#2]
however，These  function  can not run on OTB.
I think  there are some mistakes

**Comment by ixez** [comment]
Could you post the information of the mistake?

**Comment by BridgeLee** [comment]
Can you run CREST code on OTB? , I can't run CREST, but other algorithms can run

**Comment by ixez** [comment]
> Can you run CREST code on OTB? , I can't run CREST, but other algorithms can run

Post the error information

**Comment by BridgeLee** [comment]
such as :  1_CREST,1_carDark  1/1
                   error

**Comment by ixez** [comment]
Do you compile the next files?

On 12 Apr 2019, at 19:11, BridgeLee <notifications@github.com<mailto:notifications@github.com>> wrote:


such as : 1_CREST,1_carDark 1/1
error

**Comment by BridgeLee** [comment]
my  tracker  can run  ，however can  not  run on OTB。 can not  get  .mat files and OPE

**Comment by ixez** [comment]
Sorry, did you compile the mex files?

On 12 Apr 2019, at 19:26, BridgeLee <notifications@github.com<mailto:notifications@github.com>> wrote:


my tracker can run ，however can not run on OTB。 can not get .mat files and OPE

**Comment by BridgeLee** [comment]
sorry,  l  have run  mex -setup，  I do not know  what is "compile mex file"

**Comment by ixez** [comment]
Can you debug which line does it stop?
You probably need to set a breakpoint in run_CREST.

On 12 Apr 2019, at 19:58, BridgeLee <notifications@github.com<mailto:notifications@github.com>> wrote:


sorry, l have run mex -setup， I do not know what is "compile mex file"

**Comment by BridgeLee** [comment]
the  code  CREST  was run  in  linux or  windows？

**Comment by ixez** [comment]
> the code CREST was run in linux or windows？

It is tested on Linux. Did you follow `README` in `CREST` folder?
